package mypack;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.annotation.*;

@WebServlet(urlPatterns = {"/home"})
public class home extends HttpServlet {
    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse res)
            throws ServletException, IOException {
        res.setContentType("text/html");
        PrintWriter out = res.getWriter();
        HttpSession session = req.getSession();
        if (session.getAttribute("uname") == null) {
            res.sendRedirect("/crud");
        } else {
            out.println("<!DOCTYPE html>\n"
                    + "<html>\n"
                    + "\n"
                    + "<head>\n"
                    + "    <title>Start Page</title>\n"
                    + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                    + "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css\"\n"
                    + "        integrity=\"sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==\"\n"
                    + "        crossorigin=\"anonymous\" />\n"
                    + "\n"
                    + "    <link rel=\"stylesheet\" href=\"index.css\" />\n"
                    + "    <style>\n"
                    + "        li {\n"
                    + "            padding: 0;\n"
                    + "            margin: 0;\n"
                    + "        }\n"
                    + "\n"
                    + "        ul,\n"
                    + "        li {\n"
                    + "            list-style: none;\n"
                    + "        }\n"
                    + "\n"
                    + "        h1 {\n"
                    + "            text-align: center;\n"
                    + "        }\n"
                    + "\n"
                    + "        #crud {\n"
                    + "            margin-top: 50px;\n"
                    + "        }\n"
                    + "\n"
                    + "        .header {\n"
                    + "\n"
                    + "            height: 60px;\n"
                    + "        }\n"
                    + "\n"
                    + "        .column {\n"
                    + "\n"
                    + "            height: 400px;\n"
                    + "\n"
                    + "        }\n"
                    + "\n"
                    + "        .segment {\n"
                    + "            border: 2px solid black;\n"
                    + "            height: 90%;\n"
                    + "            margin-top: 20px;\n"
                    + "        }\n"
                    + "        #logout-btn{margin-left: 90%;}         "
                    + "    </style>\n"
                    + "</head>\n"
                    + "\n"
                    + "<body>\n"
                    + "    <div class=\" ui container\" id=\"main-container\">\n"
                    + "        <div class=\"ui segment\">\n"
                    + "            <h1 class=\"ui header\">CRUD OPERATIONS</h1>\n"
                    + "            <a href=\"handleLogout\" id='logout-btn' class='ui button'>Logout</a>       "
                    + "        </div>\n"
                    + "        <div class=\"ui segment\">\n"
                    + "            <div id=\"crud\">\n"
                    + "\n"
                    + "                <div class=\"ui four column grid\">\n"
                    + "                    <div class=\"column\">\n"
                    + "                        <div class=\"ui segment\">\n"
                    + "                            <i class=\"edit icon large\"></i>\n"
                    + "                            <li><a href=\"handleCreate0\">CREATE</a></li>\n"
                    + "                            <p>\n"
                    + "                                Create and persist new records to the database.\n"
                    + "                            </p>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "\n"
                    + "                    <div class=\"column\">\n"
                    + "                        <div class=\"ui segment\">\n"
                    + "                            <i class=\"book icon large\"></i>\n"
                    + "                            <li><a href=\"handleRead\">READ</a></li>\n"
                    + "                            <p>\n"
                    + "                                Fetch and display records from the database.\n"
                    + "                            </p>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "\n"
                    + "                    <div class=\"column\">\n"
                    + "                        <div class=\"ui segment\">\n"
                    + "                            <i class=\"pencil icon large\"></i>\n"
                    + "                            <li><a href=\"handleUpdate\">UPDATE</a></li>\n"
                    + "                            <p>\n"
                    + "                                Update existing records by selecting and passing id.\n"
                    + "                            </p>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "\n"
                    + "                    <div class=\"column\">\n"
                    + "                        <div class=\"ui segment\">\n"
                    + "                            <i class=\"trash icon large\"></i>\n"
                    + "                            <li><a href=\"handleDelete\">DELETE</a></li>\n"
                    + "                            <p>\n"
                    + "                                Delete existing record permanently from the database.\n"
                    + "                            </p>\n"
                    + "                        </div>\n"
                    + "                    </div>\n"
                    + "\n"
                    + "                </div>\n"
                    + "            </div>\n"
                    + "        </div>\n"
                    + "    </div>\n"
                    + "\n"
                    + "</body>\n"
                    + "\n"
                    + "</html>");
        }
    }
}
